### ISSUE TITLE
[Bug]: No shipping bin

### ISSUE THREAD

**Issue by danielhieng** [agilbert1412/StardewArchipelago#12]
When creating a new farm with any farm, there is no shipping bin for players to use sometimes

**Comment by agilbert1412** [comment]
Are you playing with shuffled buildings? because that includes the shipping bin, it is an Archipelago item that must be found, or sent to you by someone else if playing with other players

**Comment by danielhieng** [comment]
for building progression, I had it set to progressive early shipping bin, so I'm assuming that it has to be found first then?

**Comment by agilbert1412** [comment]
Yes, it still needs to be found. The early settings only garantees that it is possible to find the shipping bin early (for example, it cannot be on floor 120 of the mines, as that would be too late). So someone, somewhere in your multiworld, can theoretically go grab your shipping bin immediately, right off the bat at start. It will not be locked behind anything. But it is still randomized, so you don't know where it is. Just that it's accessible quickly

**Comment by danielhieng** [comment]
Ok, thanks for your help! :)
