### ISSUE TITLE
Gender-locked spa room

### ISSUE THREAD

**Issue by EmilyV99** [agilbert1412/StardewArchipelago#29]
When finding the spa entrance, you can only go in the door that corresponds with your chosen gender. However, if you use the wizard's shrine to change your gender, you become locked out of whatever room was randomly (entrance shuffle) behind that door (the new gender door leads to the actual spa, instead of the randomized location). I would assume both of these doors should lead to the same destination to prevent this...

**Comment by agilbert1412** [comment]
Simply reload the game after changing gender. The spa room, and all other entrance randomizations, happen at game load when connecting to archipelago. It checks your gender at that moment, and will re-do the check upon doing a save-load cycle.
