### ISSUE TITLE
[Bug]: Bulletin Board Covered By Bush

### ISSUE THREAD

**Issue by melodyserafina** [agilbert1412/StardewArchipelago#30]
Hi there,

On the first day of my third season, I got the cutscene where Robin and Lewis say they've built a large bulletin board in the south of town below Lewis' house. But the bush remained in that area and I can't click it to access the weekly quests. I waited a full season until I unlocked Fall to make sure it wasn't locked behind Fall but I still don't have access to it on Fall 2nd (my 4th season in game). Please advise on what I should do next so that I have access to those quests and the locations checks on it. Thank you!

**Comment by agilbert1412** [comment]
The Special Order Board is an Archipelago item to be received. Once you get it, the board will appear and be available.
The cutscene plays on a specific date regardless of if you actually have the board unlocked or not, like many other cutscenes based on randomized features

**Comment by melodyserafina** [comment]
Thank you!
