### ISSUE TITLE
Stardew valley port change?

### ISSUE THREAD

**Issue by FluffyChan06** [agilbert1412/StardewArchipelago#39]
I've been playing on my stardew world for a few days now and have had no issues till now and its a weird one, When I went to log into my world today it wouldn't let me, kept saying it couldn't connect to the server so I tried to see what happened.

it seems like the port changed over night and now it wont let me play on my world, I have no idea why or how this happened as it worked fine when I logged of yesterday. (image shows how it changed)

I've tried to do the connect commend but I don't think I did it right, I've restarted my pc and the game but I honestly don't know how to fix this or what to do (posted on discord too)
https://archipelago.gg/room/xO-ArpIJTNyLpxrEEsCOGA
![Screenshot (5)](https://github.com/agilbert1412/StardewArchipelago/assets/158232889/c7acd717-afc8-4a8d-88cb-4efb84d86a96)
![Screenshot (7)](https://github.com/agilbert1412/StardewArchipelago/assets/158232889/df81c8d8-9091-43f0-8d67-9026792293a4)

**Comment by agilbert1412** [comment]
This is not a bug, it's part of how Archipelago works. You can use the `connect_override` command to get back into your slot
