### ISSUE TITLE
[feature request] have your partner recognize whether a child is to be born or adopted

### ISSUE THREAD

**Issue by VyseGolbez** [agilbert1412/StardewArchipelago#47]
As I am currently playing in a 4.x.x seed, I am running the risk that this is one of the things that is actually already different in 5.x.x.

Currently, regardless of the player's gender, your partner will ask about "giving birth" to \<insert multiworld item here\>. For same sex couples, the conversation text during the time between the question and the child being there/item being sent still references an adoption though. As such, it would make sense if a same sex partner would instead ask to adopt \<insert multiworld item here\>.

**Comment by agilbert1412** [comment]
Fixed in https://github.com/agilbert1412/StardewArchipelago/releases/tag/5.5.3
