### ISSUE TITLE
[Stardew Valley] No friendship gain on MAC OS, but works on Windows/Linux

### ISSUE THREAD

**Issue by Jyvent** [agilbert1412/StardewArchipelago#5]
We have a strange bug on Mac OS on my wife's computer. She has recently updated to MAS OS Ventura and has noticed that when she plays she will never gain friendship with any NPC's. 

She has played before updating the MAC and everything worked perfectly. This was on an older version.

I have tested with my Steam deck and a Windows computer using the same server and it works for me on those. but move back to the MAC and it does not work.

For clarity, we are running the latest versions of SMAPI 3.18.4 and Archipelago 3.4.2. We noticed even on the previous issue of the mod it wasn't working.

We have made a few games and are all the same. Not sure what you need to test this. The easiest way we have found to know if it working or not is to create a room with friendsanity and then login to the and start and then release the player and see if the friendship goes up or not.

Thanks for all you do!
Regards, Daniel

**Comment by agilbert1412** [comment]
Hello! Sorry for the late answer, I had actually completely missed this report.

I've been working with someone who has the same issue (again on a Mac) to try to figure it out.

The latest release should help!
https://github.com/agilbert1412/StardewArchipelago/releases/tag/4.6.0

It will only update a friendship once it changes, so talk to people and you should get your points! Even the points earned before the fix!
