### ISSUE TITLE
Skill Progression Does Not Show Checked Level in Game

### ISSUE THREAD

**Issue by GFreak01** [agilbert1412/StardewArchipelago#56]
When having Skill Progression set to Progressive, the in-game display is set to the acquired level.  However there is no display (unless I've missed it) showing what level has been "checked".

Example, I've been given up to Mining Level 4, and I've checked up to Mining Level 8.  I have to use the multiworld tracker to see that I still need to mine more for checks.

**Comment by agilbert1412** [comment]
The display is the `!!experience` command. I am not good at UI and I haven't found a way to make an actual visual UI that looks good. It is also not a priority for me, so it is unlikely I'll make one in the near future.

I'm open to someone PRing one, but in the meantime, this is "as intended", even if not ideal
