### ISSUE TITLE
Feature Request: Movement Speed Bonus Control

### ISSUE THREAD

**Issue by GFreak01** [agilbert1412/StardewArchipelago#57]
Could we get a hotkey for the "Permanent Movement Speed Bonuses"?
Perhaps turn it into a press-to-sprint or toggle?

I am moving very quickly, and it is a little hard to control when I need fine movements.

**Comment by agilbert1412** [comment]
Isn't the already-built-in walk toggle good enough?

**Comment by GFreak01** [comment]
Sorry, I use a controller.  I tried walking and it still moves very quickly.

**Comment by agilbert1412** [comment]
I released a config option for this in [Release 5.5.2](https://github.com/agilbert1412/StardewArchipelago/releases/tag/5.5.2)
