### ISSUE TITLE
FileNotFoundException due to file case mismatch

### ISSUE THREAD

**Issue by AnOctopus** [agilbert1412/StardewArchipelago#6]
I installed the 4.5.3 release to play with the new settings, but it mostly failed to load (the starting season was changed, but nothing else appeared to have loaded). After launching from a terminal to see logs, I saw 3 errors, one of which mentioned that `Stardew Valley/Content/Data/Hats.xnb` could not be found. In that directory, there is instead a `hats.xnb` (and a bunch of versions for other languages, all lowercase), and most files in the directory start with uppercase names. I use linux, and have a case sensitive filesystem. Creating a symlink with the appropriately capitalized name caused it to launch without issue, and it appears to load correctly.

I haven't specifically noticed errors for other things with lowercase data files in that directory, but it could be worth checking the case the code is expecting for those too, just in case.

**Comment by agilbert1412** [comment]
Can you send a screenshot or a text copy of the error message, or even better, the whole SMAPI log for a failed run?
It would help me figure out what I'm doing wrong, compared to other mods that need to load these files

**Comment by agilbert1412** [comment]
I think this should fix your issue
https://github.com/agilbert1412/StardewArchipelago/releases/tag/4.5.4
