### ISSUE TITLE
[Bug]: Island shuffling: Parrot goals unobtainable

### ISSUE THREAD

**Issue by annaroth01** [agilbert1412/StardewArchipelago#7]
When including island items in shuffling, the following problem appears: If you obtain a reward before paying the respective parrots, you can't get that anymore. 

E. g.; I unlocked the volcano bridge very early in the game so the parrot for that disappeared. However, my skull key is locked behind that parrot, making it impossible for me to enter skull cavern and completing the respective Qi quest, which in turn locks Maru hearts, which prevents me from reaching my goal (Perfection).

**Comment by agilbert1412** [comment]
Are you sure that it disappeared? As opposed to having never been there in the first place?

This parrot will only spawn once you have attained two conditions
1: Reached the Forge at the top of the volcano
2: Removed the Turtle to Island West

The first condition is in your hands, but the 2nd condition is a multiworld item to be received. Did you receive it, and has the turtle moved? Until it moves, the Volcano bridge parrot will never spawn.

All parrots are like this in archipelago. They keep their original spawn conditions, which are often based on other Archipelago received items, even if you receive the item that this specific parrot usually provides.

Please double check, and if there is indeed a bug, please contact me on discord to DM me your save file so I can investigate

**Comment by annaroth01** [comment]
It was the conditions, so not a bug; parrot is there now. Well, I learn something new every day.

Thank you for the quick reply, and sorry for the inconvenience! This was completely my fault.

**Comment by agilbert1412** [comment]
No problem, have fun on the mod!
