### ISSUE TITLE
Dying due to DeathLink during a cutscene causes the player to spawn in a wall

### ISSUE THREAD

**Issue by thislooksfun** [agilbert1412/StardewArchipelago#8]
Steps to reproduce:

1. Follow the Stardew setup guide
2. Start an Archipelago game with DeathLink enabled
3. Enter a cutscene in Stardew
4. Die in another game with DeathLink enabled
5. The player in Stardew will die and respawn softlocked in the wall of the clinic

**Comment by agilbert1412** [comment]
@thislooksfun Some interactions with various archipelago elements, deathlink and entrance randomizer being the two most common ones, can get the player stuck in a wall.

There is a chat command you can use, "!!unstuck", which should free you and allow you to continue on with your day. You can also use "!!sleep" at any point to pass out (same consequences as the 2AM pass out) instantly
